-- Comments Schema for SmartAktau
-- Run this in Supabase SQL Editor to add comments functionality

-- Create comments table
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  author_role TEXT DEFAULT 'user', -- 'user', 'admin', 'service'
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_comments_complaint_id ON comments(complaint_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);

-- Create updated_at trigger for comments
DROP TRIGGER IF EXISTS update_comments_updated_at ON comments;
CREATE TRIGGER update_comments_updated_at
    BEFORE UPDATE ON comments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (demo/hackathon purposes)
-- Allow anyone to read comments
CREATE POLICY "Allow public read access" ON comments
    FOR SELECT
    USING (true);

-- Allow anyone to insert comments (users can comment)
CREATE POLICY "Allow public insert access" ON comments
    FOR INSERT
    WITH CHECK (true);

-- Allow anyone to update their own comments (for demo)
-- In production, restrict to comment author only
CREATE POLICY "Allow public update access" ON comments
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

-- Delete policy (restricted - only for admins via service_role key)
CREATE POLICY "Allow service role delete access" ON comments
    FOR DELETE
    USING (auth.jwt()->>'role' = 'service_role');

-- Add comments to table
COMMENT ON TABLE comments IS 'Comments and responses for SmartAktau complaints';
COMMENT ON COLUMN comments.author_role IS 'Role: user (citizen), admin (city staff), or service (system)';
COMMENT ON COLUMN comments.text IS 'Comment text content';

-- Function to get comments count for a complaint
CREATE OR REPLACE FUNCTION get_comments_count(complaint_bigint BIGINT)
RETURNS BIGINT AS $$
BEGIN
    RETURN (SELECT COUNT(*) FROM comments WHERE complaint_id = complaint_bigint);
END;
$$ LANGUAGE plpgsql;

-- Add comments_count column to complaints (optional, for performance)
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS comments_count INTEGER DEFAULT 0;

-- Function to update comments count
CREATE OR REPLACE FUNCTION update_complaint_comments_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE complaints
        SET comments_count = comments_count + 1
        WHERE id = NEW.complaint_id;
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE complaints
        SET comments_count = comments_count - 1
        WHERE id = OLD.complaint_id;
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update comments_count
DROP TRIGGER IF EXISTS update_comments_count_trigger ON comments;
CREATE TRIGGER update_comments_count_trigger
    AFTER INSERT OR DELETE ON comments
    FOR EACH ROW
    EXECUTE FUNCTION update_complaint_comments_count();

-- Initialize comments_count for existing complaints
UPDATE complaints
SET comments_count = (
    SELECT COUNT(*)
    FROM comments
    WHERE comments.complaint_id = complaints.id
);
