-- SmartAktau Database Schema
-- Run this in Supabase SQL Editor to create the complaints table

-- Create complaints table
CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id TEXT UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  status TEXT DEFAULT 'Получено',
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  address TEXT DEFAULT 'Актау',
  photo_urls TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_complaints_created_at ON complaints(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_complaints_category ON complaints(category);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_public_id ON complaints(public_id);

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update updated_at
DROP TRIGGER IF EXISTS update_complaints_updated_at ON complaints;
CREATE TRIGGER update_complaints_updated_at
    BEFORE UPDATE ON complaints
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (demo/hackathon purposes)
-- Allow anyone to read complaints
CREATE POLICY "Allow public read access" ON complaints
    FOR SELECT
    USING (true);

-- Allow anyone to insert complaints (anon key can create)
CREATE POLICY "Allow public insert access" ON complaints
    FOR INSERT
    WITH CHECK (true);

-- Allow anyone to update complaints (for status changes in admin panel)
-- In production, this should be restricted to authenticated admins only
CREATE POLICY "Allow public update access" ON complaints
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

-- IMPORTANT: For production, replace the update policy with:
-- CREATE POLICY "Allow authenticated update access" ON complaints
--     FOR UPDATE
--     USING (auth.role() = 'authenticated')
--     WITH CHECK (auth.role() = 'authenticated');

-- Delete policy (restricted - only for admins via service_role key)
CREATE POLICY "Allow service role delete access" ON complaints
    FOR DELETE
    USING (auth.jwt()->>'role' = 'service_role');

-- Add comment to table
COMMENT ON TABLE complaints IS 'SmartAktau citizen complaints and reports';

-- Add comments to important columns
COMMENT ON COLUMN complaints.public_id IS 'Public-facing ID (format: ACT-timestamp)';
COMMENT ON COLUMN complaints.status IS 'Status: Получено, В обработке, or Выполнено';
COMMENT ON COLUMN complaints.category IS 'Category: water, garbage, lighting, roads, or other';
COMMENT ON COLUMN complaints.photo_urls IS 'Array of photo URLs from Storage bucket';
